name: russia_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  shared_preferences: ^2.3.3
  easy_localization: ^3.0.8
  google_fonts: ^8.0.0
  custom_refresh_indicator: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/translations/
    - lib/assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/logo.png"
  min_sdk_android: 21 
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: "lib/assets/logo_padded.png"
  android_12:
    image: "lib/assets/logo_padded.png"
    color: "#ffffff"
